config/routes.rb
Rails.application.routes.draw do
  root "phonebooks#index"
  resources :phonebooks

  get "api/phonebooks/indexData", to: "phonebooks#api_indexData"
  get "api/phonebooks/counter", to: "phonebooks#api_counter", as: "api_contact_counter"
  # get "api/phonebooks/:id", to: "phonebooks#api_show"
  # put "api/phonebooks/:id", to: "phonebooks#api_update"
  # post "api/phonebooks/", to: "phonebooks#api_create"
  # delete "api/phonebooks/:id", to: "phonebooks#api_destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/phonebook.rb
class Phonebook < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phonebooks_controller.rb
class PhonebooksController < ApplicationController
    def index
        @count_contacts = Phonebook.count
        @phonebooks = Phonebook.all
    end

    def show
        @phonebook = Phonebook.find(params[:id])

        respond_to do |format|
            format.html
            format.json {render json: @phonebook, status: :ok}
        end
    end

    def new
        @phonebook = Phonebook.new()
    end

    def create
        @phonebook = Phonebook.new(phonebook_params)

        if @phonebook.save
            respond_to do |format|
                format.html {redirect_to @phonebook}
                format.json {render json: {response: "Data Berhasil Tersimpan"}, status: :ok}
            end
        else
            respond_to do |format|
                format.html {render :new, status: :unprocessable_entity}
                format.json {render json: {response: "Data Gagal Tersimpan"}, status: :unprocessable_entity}
            end
        end
    end

    def edit
        @phonebook = Phonebook.find(params[:id])
    end

    def update
        @phonebook = Phonebook.find(params[:id])

        if @phonebook.update(phonebook_params)
            respond_to do |format|
                format.html {redirect_to @phonebook}
                format.json {render json: {response: "Data Berhasil Terubah"}, status: :ok}
            end
        else
            respond_to do |format|
                format.html {render :edit, status: :unprocessable_entity}
                format.json {render json: {response: "Data Berhasil Terubah"}, status: :ok}
            end
        end
    end

    def destroy
        @phonebook = Phonebook.find(params[:id])
        @phonebook.destroy

        respond_to do |format|
            format.html {redirect_to phonebooks_path, status: :see_other}
            format.json {render json: {response: "Data Berhasil Dihapus"}, status: :ok}
        end
    end

    def api_indexData
        @count_contacts = Phonebook.count
        @phonebook = Phonebook.select("first_name, last_name, id")
        render json: {contacts: @phonebook, count_contacts: @count_contacts}, status: :ok
    end

    # def api_show
    #     @phonebook = Phonebook.find(params[:id])
    #     render json: @phonebook, status: :ok
    # end

    # def api_update
    #     @phonebook = Phonebook.find(params[:id])

    #     if @phonebook.update(phonebook_params)
    #         render json: {response: "Data Berhasil Terubah"}, status: :ok
    #     else
    #         render json: {response: "Data Gagal Tersimpan"}, status: :unprocessable_entity
    #     end
    # end

    # def api_create
    #     @phonebook = Phonebook.new(phonebook_params)

    #     if @phonebook.save
    #         render json: {response: "Data Berhasil Tersimpan"}, status: :ok
    #     else
    #         render json: {response: "Data Gagal Tersimpan"}, status: :unprocessable_entity
    #     end
    # end

    # def api_destroy
    #     @phonebook = Phonebook.find(params[:id])
    #     @phonebook.destroy

    #     render json: {response: "Data Berhasil Dihapus"}, status: :ok
    # end

    private
        def phonebook_params
            params.require(:phonebook).permit(:first_name, :last_name, :email, :phone, :instagram, :twitter, :linkedin, :tag)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebooks <%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield :content %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <%= yield :js_after %>
  </body>
</html>

app/views/phonebooks/_form.html.erb
<%= form_with model: @phonebook do |form| %>
    <div class="input-group m-3">
        <%= form.label :first_name ,class: "input-group-text"%><br>
        <%= form.text_field :first_name, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:first_name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :last_name ,class: "input-group-text"%><br>
        <%= form.text_field :last_name, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:last_name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :tag ,class: "input-group-text"%><br>
        <%= form.text_field :tag, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:tag).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :email ,class: "input-group-text"%><br>
        <%= form.email_field :email, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:email).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :phone ,class: "input-group-text"%><br>
        <%= form.text_field :phone, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:phone).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :instagram ,class: "input-group-text"%><br>
        <%= form.text_field :instagram, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:instagram).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :twitter ,class: "input-group-text"%><br>
        <%= form.text_field :twitter, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:twitter).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="input-group m-3">
        <%= form.label :linkedin ,class: "input-group-text"%><br>
        <%= form.text_field :linkedin, class: "form-control"%>
        <% @phonebook.errors.full_messages_for(:linkedin).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="d-flex-row justify-content-between">
        <div class="col-5">
            <%= form.submit class: "btn btn-success"%>
        </div>
    </div>
<% end %>

app/views/phonebooks/edit.html.erb
<% content_for :title do %>
- Ubah Kontak
<% end %>
<% content_for :content do %>
<div class="d-flex justify-content-between m-3">
    <h1>Ubah Kontak</h1>
    <%= link_to "Kembali", phonebooks_path , class: "btn btn-sm btn-primary"%>
</div>


<%= render "form", phonebook: @phonebook %>
<% end %>

app/views/phonebooks/index.html.erb
<% content_for :title do %>
<% end %>
<% content_for :content do %>
<div class="row mt-3">
    <h1>Daftar Kontak</h1>
</div>
<div class="row m-3">
    <div class="card text-bg-success">
        <div class="card-body">
        <div class="card-text">Jumlah Kontak Tersimpan</div>
        <div class="card-title text-end"><h3 id="contact-count">0</h3></div>
        </div>
    </div>
</div>
<div class="row m-3">
    <table class="table table-striped-columns table-hover">
        <thead>
            <tr>
                <th>Nama Lengkap</th>
                <th><button class="btn btn-sm btn-create btn-info" data-bs-toggle="modal">Tambah</button></th>
            </tr>
        </thead>
        <tbody id="phonebook-table">
        <%if @phonebooks.empty?%>
        <h3>Belum Ada Kontak Terdaftar</h3>
        <%end%>
        </tbody>
    </table>
</div>
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="modal-detail">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detail Data</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            </div>
            <div class="modal-body">
                <dl class="row" id="detail-field">
                </dl>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-bs-backdrop="static" id="modal-form-create">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Form</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            </div>
            <div class="modal-body">
            <div class="card text-bg-danger" hidden>
                <div class="container m2" id="error-card-field">
                </div>
            </div>
                <div class="row col-12">
                    <form id="form-modal-create">
                        <input class="form-control" type="hidden" name="id"/>
                        <div class="input-group m-3">
                            <label class="input-group-text">Nama Depan</label>
                            <input class="form-control" name="first_name" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Nama Belakang</label>
                            <input class="form-control" name="last_name" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Tag</label>
                            <input class="form-control" name="tag"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Email</label>
                            <input type="email" class="form-control" name="email"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Telepon</label>
                            <input class="form-control" name="phone" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Instagram</label>
                            <input class="form-control" name="instagram"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Twitter</label>
                            <input class="form-control" name="twitter"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Linkedin</label>
                            <input class="form-control" name="linkedin"/>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-submit-create">Submit</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-bs-backdrop="static" id="modal-form-edit">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Form</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            </div>
            <div class="modal-body">
            <div class="card text-bg-danger" hidden>
                <div class="container m2" id="error-card-field">
                </div>
            </div>
                <div class="row col-12">
                    <form id="form-modal-edit">
                        <input class="form-control" type="hidden" name="id"/>
                        <div class="input-group m-3">
                            <label class="input-group-text">Nama Depan</label>
                            <input class="form-control" name="first_name" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Nama Belakang</label>
                            <input class="form-control" name="last_name" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Tag</label>
                            <input class="form-control" name="tag"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Email</label>
                            <input type="email" class="form-control" name="email"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Telepon</label>
                            <input class="form-control" name="phone" required/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Instagram</label>
                            <input class="form-control" name="instagram"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Twitter</label>
                            <input class="form-control" name="twitter"/>
                        </div>
                        <div class="input-group m-3">
                            <label class="input-group-text">Linkedin</label>
                            <input class="form-control" name="linkedin"/>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-submit-edit">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="toast-container position-absolute p-3 top-0 end-0">
    <div class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true" id="toast-success">
        <div class="d-flex">
            <div class="toast-body" id="toast-alert-success">
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<%end%>

<% content_for :js_after do %>
    <%= javascript_include_tag "phonebook/index.js", "data-turbolinks-track" => true %>
<% end %>

app/views/phonebooks/new.html.erb
<% content_for :title do %>
- Tambah Kontak
<% end %>
<% content_for :content do %>
<div class="d-flex justify-content-between m-3">
    <h1>Tambah Kontak</h1>
    <%= link_to "Kembali", phonebooks_path , class: "btn btn-sm btn-primary"%>
</div>

<%= render "form", phonebook: @phonebook %>
<% end %>

app/views/phonebooks/show.html.erb
<% content_for :title do %>
- <%=@phonebook.first_name+" "+@phonebook.last_name%>
<% end %>
<% content_for :content do %>
<div class="row m-3">
    <h1><%=@phonebook.first_name+" "+@phonebook.last_name%></h1>
</div>

<div class="d-flex flex-row-reverse">
    <div class="button-group">
        <%= link_to "Kembali", phonebooks_path, class: "btn btn-sm btn-primary"%>
        <%= link_to "Ubah", edit_phonebook_path(@phonebook), class: "btn btn-sm btn-warning" %>
        <%= link_to "Hapus", phonebook_path(@phonebook), data:{ turbo_method: :delete, turbo_confirm: :"Apakah anda yakin menghapus data ini?"}, class: "btn btn-sm btn-danger" %>
    </div>
</div>

<div class="row">
    <dl class="row">
        <dt>Email</dt>
        <dd><%=@phonebook.email%></dd>
        <dt>Phone</dt>
        <dd><%=@phonebook.phone%></dd>
        <dt>Instagram</dt>
        <dd><a href="https://www.instagram.com/<%=@phonebook.instagram%>"><%=@phonebook.instagram%></a></dd>
        <dt>Twitter</dt>
        <dd><a href="https://www.twitter.com/<%=@phonebook.twitter%>"><%=@phonebook.twitter%></a></dd>
        <dt>Linkedin</dt>
        <dd><a href="https://www.linkedin.com/in/<%=@phonebook.linkedin%>"><%=@phonebook.linkedin%></a></dd>
        <dt>Tag</dt>
        <dd><%=@phonebook.tag%></dd>
    </dl>
</div>
<% end %>